// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NivBot.DataLayer;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NivBot.Migrations
{
    [DbContext(typeof(GoodplaceContext))]
    partial class GoodplaceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NivBot.DataLayer.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OsrsId")
                        .HasColumnType("integer");

                    b.Property<string>("OsrsName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OsrsName")
                        .IsUnique();

                    b.ToTable("Activities", t =>
                        {
                            t.HasCheckConstraint("CK_Activity_OsrsName", "length(\"OsrsName\") <= 100");

                            t.HasCheckConstraint("CK_Activity_Points", "\"Points\" >= 0 AND \"Points\" <= 1000");
                        });
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.ActivityCompetition", b =>
                {
                    b.Property<int>("CompetitionProviderDetailsId")
                        .HasColumnType("integer");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CompetitionProviderDetailsId");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityCompetitions");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.ActivityLog", b =>
                {
                    b.Property<int>("RunescapeAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("RunescapeAccountId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityLogs", t =>
                        {
                            t.HasCheckConstraint("CK_ActivityLog_Amount", "\"Amount\" >= 0");
                        });
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.ActivityRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<long?>("DiscordRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("DiscordRoleId")
                        .IsUnique();

                    b.ToTable("ActivityRanks");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.ActivityTaskBlocklist", b =>
                {
                    b.Property<int>("GoodplaceUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.HasKey("GoodplaceUserId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityTaskBlockLists");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.CollectionLog", b =>
                {
                    b.Property<int>("RunescapeAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("RunescapeAccountId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CollectionLogs", t =>
                        {
                            t.HasCheckConstraint("CK_CollectionLog_Amount", "\"Amount\" >= 0");
                        });
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.CompetitionProviderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompetitionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompetitionProvider")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId", "CompetitionProvider")
                        .IsUnique();

                    b.ToTable("CompetitionProvidersDetails");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.DiscordMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("DiscordMessages");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.DiscordRole", b =>
                {
                    b.Property<long>("DiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiscordId"));

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DiscordId");

                    b.ToTable("DiscordRoles");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.GlobalActivityBlocklist", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.HasKey("ActivityId");

                    b.ToTable("GlobalActivityBlockLists");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.GoodplaceActivityTask", b =>
                {
                    b.Property<int>("GoodplaceUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentCumulativeAmount")
                        .HasColumnType("integer");

                    b.Property<int>("GoalAmount")
                        .HasColumnType("integer");

                    b.HasKey("GoodplaceUserId");

                    b.HasIndex("ActivityId");

                    b.ToTable("GoodplaceActivityTasks");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.GoodplaceSkillTask", b =>
                {
                    b.Property<int>("GoodplaceUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.Property<long>("GoalXp")
                        .HasColumnType("bigint");

                    b.Property<long>("SummedCurrentXp")
                        .HasColumnType("bigint");

                    b.HasKey("GoodplaceUserId", "Skill");

                    b.HasIndex("GoodplaceUserId")
                        .IsUnique();

                    b.HasIndex("Skill");

                    b.ToTable("GoodplaceSkillTasks");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.GoodplaceUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.ToTable("GoodplaceUsers");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OsrsId")
                        .HasColumnType("integer");

                    b.Property<string>("OsrsName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items", t =>
                        {
                            t.HasCheckConstraint("CK_Item_OsrsName", "length(\"OsrsName\") <= 100");

                            t.HasCheckConstraint("CK_Item_Points", "\"Points\" >= 0 AND \"Points\" <= 1000");
                        });
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.RunescapeAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GoodplaceUserId")
                        .HasColumnType("integer");

                    b.Property<string>("RunescapeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("syncedColLog")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GoodplaceUserId");

                    b.HasIndex("RunescapeName")
                        .IsUnique();

                    b.ToTable("RunescapeAccounts");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.RunescapeStat", b =>
                {
                    b.Property<int>("RunescapeAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("RunescapeAccountId", "Skill");

                    b.HasIndex("Skill");

                    b.ToTable("RunescapeStats", t =>
                        {
                            t.HasCheckConstraint("CK_RunescapeStat_Xp", "\"Xp\" >= 0 AND \"Xp\" <= 200000000");
                        });
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("HiscoreIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HiscoreIndex")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HiscoreIndex = 1,
                            Name = "Attack"
                        },
                        new
                        {
                            Id = 2,
                            HiscoreIndex = 2,
                            Name = "Defence"
                        },
                        new
                        {
                            Id = 3,
                            HiscoreIndex = 3,
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 4,
                            HiscoreIndex = 4,
                            Name = "Hitpoints"
                        },
                        new
                        {
                            Id = 5,
                            HiscoreIndex = 5,
                            Name = "Ranged"
                        },
                        new
                        {
                            Id = 6,
                            HiscoreIndex = 6,
                            Name = "Prayer"
                        },
                        new
                        {
                            Id = 7,
                            HiscoreIndex = 7,
                            Name = "Magic"
                        },
                        new
                        {
                            Id = 8,
                            HiscoreIndex = 8,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 9,
                            HiscoreIndex = 9,
                            Name = "Woodcutting"
                        },
                        new
                        {
                            Id = 10,
                            HiscoreIndex = 10,
                            Name = "Fletching"
                        },
                        new
                        {
                            Id = 11,
                            HiscoreIndex = 11,
                            Name = "Fishing"
                        },
                        new
                        {
                            Id = 12,
                            HiscoreIndex = 12,
                            Name = "Firemaking"
                        },
                        new
                        {
                            Id = 13,
                            HiscoreIndex = 13,
                            Name = "Crafting"
                        },
                        new
                        {
                            Id = 14,
                            HiscoreIndex = 14,
                            Name = "Smithing"
                        },
                        new
                        {
                            Id = 15,
                            HiscoreIndex = 15,
                            Name = "Mining"
                        },
                        new
                        {
                            Id = 16,
                            HiscoreIndex = 16,
                            Name = "Herblore"
                        },
                        new
                        {
                            Id = 17,
                            HiscoreIndex = 17,
                            Name = "Agility"
                        },
                        new
                        {
                            Id = 18,
                            HiscoreIndex = 18,
                            Name = "Thieving"
                        },
                        new
                        {
                            Id = 19,
                            HiscoreIndex = 19,
                            Name = "Slayer"
                        },
                        new
                        {
                            Id = 20,
                            HiscoreIndex = 20,
                            Name = "Farming"
                        },
                        new
                        {
                            Id = 21,
                            HiscoreIndex = 21,
                            Name = "Runecrafting"
                        },
                        new
                        {
                            Id = 22,
                            HiscoreIndex = 22,
                            Name = "Hunter"
                        },
                        new
                        {
                            Id = 23,
                            HiscoreIndex = 23,
                            Name = "Construction"
                        },
                        new
                        {
                            Id = 24,
                            HiscoreIndex = 24,
                            Name = "Sailing"
                        });
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.SkillCompetition", b =>
                {
                    b.Property<int>("CompetitionProviderDetailsId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CompetitionProviderDetailsId");

                    b.HasIndex("Skill");

                    b.ToTable("SkillCompetitions");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.SkillRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<long?>("DiscordRoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscordRoleId")
                        .IsUnique();

                    b.ToTable("SkillRanks");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.SkillTaskBlocklist", b =>
                {
                    b.Property<int>("GoodplaceUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.HasKey("GoodplaceUserId", "Skill");

                    b.HasIndex("Skill");

                    b.ToTable("SkillTaskBlockLists");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.Wallet", b =>
                {
                    b.Property<int>("GoodplaceUserId")
                        .HasColumnType("integer");

                    b.Property<int>("GoodplaceCurrency")
                        .HasColumnType("integer");

                    b.Property<int>("GoodplacePoints")
                        .HasColumnType("integer");

                    b.HasKey("GoodplaceUserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.ActivityCompetition", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NivBot.DataLayer.Models.CompetitionProviderDetails", "CompetitionProviderDetails")
                        .WithOne()
                        .HasForeignKey("NivBot.DataLayer.Models.ActivityCompetition", "CompetitionProviderDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("CompetitionProviderDetails");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.ActivityLog", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NivBot.DataLayer.Models.RunescapeAccount", "RunescapeAccount")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("RunescapeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("RunescapeAccount");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.ActivityRank", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NivBot.DataLayer.Models.DiscordRole", "DiscordRole")
                        .WithOne()
                        .HasForeignKey("NivBot.DataLayer.Models.ActivityRank", "DiscordRoleId");

                    b.Navigation("Activity");

                    b.Navigation("DiscordRole");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.ActivityTaskBlocklist", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NivBot.DataLayer.Models.GoodplaceUser", "GoodplaceUser")
                        .WithMany("ActivityBlocks")
                        .HasForeignKey("GoodplaceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("GoodplaceUser");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.CollectionLog", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NivBot.DataLayer.Models.RunescapeAccount", "RunescapeAccount")
                        .WithMany("CollectionLogs")
                        .HasForeignKey("RunescapeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RunescapeAccount");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.GlobalActivityBlocklist", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.Activity", "Activity")
                        .WithOne()
                        .HasForeignKey("NivBot.DataLayer.Models.GlobalActivityBlocklist", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.GoodplaceActivityTask", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NivBot.DataLayer.Models.GoodplaceUser", "GoodplaceUser")
                        .WithOne("GoodplaceActivityTask")
                        .HasForeignKey("NivBot.DataLayer.Models.GoodplaceActivityTask", "GoodplaceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("GoodplaceUser");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.GoodplaceSkillTask", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.GoodplaceUser", "GoodplaceUser")
                        .WithOne("GoodplaceSkillTask")
                        .HasForeignKey("NivBot.DataLayer.Models.GoodplaceSkillTask", "GoodplaceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NivBot.DataLayer.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("Skill")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodplaceUser");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.RunescapeAccount", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.GoodplaceUser", "GoodplaceUser")
                        .WithMany("RunescapeAccounts")
                        .HasForeignKey("GoodplaceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodplaceUser");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.RunescapeStat", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.RunescapeAccount", "RunescapeAccount")
                        .WithMany("RunescapeStats")
                        .HasForeignKey("RunescapeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NivBot.DataLayer.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("Skill")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RunescapeAccount");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.SkillCompetition", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.CompetitionProviderDetails", "CompetitionProviderDetails")
                        .WithOne()
                        .HasForeignKey("NivBot.DataLayer.Models.SkillCompetition", "CompetitionProviderDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NivBot.DataLayer.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("Skill")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionProviderDetails");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.SkillRank", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.DiscordRole", "DiscordRole")
                        .WithOne()
                        .HasForeignKey("NivBot.DataLayer.Models.SkillRank", "DiscordRoleId");

                    b.Navigation("DiscordRole");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.SkillTaskBlocklist", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.GoodplaceUser", "GoodplaceUser")
                        .WithMany("SkillBlocks")
                        .HasForeignKey("GoodplaceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NivBot.DataLayer.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("Skill")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodplaceUser");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.Wallet", b =>
                {
                    b.HasOne("NivBot.DataLayer.Models.GoodplaceUser", "GoodplaceUser")
                        .WithOne("Wallet")
                        .HasForeignKey("NivBot.DataLayer.Models.Wallet", "GoodplaceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodplaceUser");
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.GoodplaceUser", b =>
                {
                    b.Navigation("ActivityBlocks");

                    b.Navigation("GoodplaceActivityTask")
                        .IsRequired();

                    b.Navigation("GoodplaceSkillTask")
                        .IsRequired();

                    b.Navigation("RunescapeAccounts");

                    b.Navigation("SkillBlocks");

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("NivBot.DataLayer.Models.RunescapeAccount", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("CollectionLogs");

                    b.Navigation("RunescapeStats");
                });
#pragma warning restore 612, 618
        }
    }
}
